### ISSUE TITLE
Only send notification for enabled apps

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#235]
### Steps

1. Install customgroups version 0.1.0 from tarball with `occ market:install --local customgroups.tar.bz2`
1. Make sure the app is disabled
1. Make sure notifications app is enabled
1. Wait a bit / refresh web UI

### Expected
No update notifications for disabled apps.

### Actual
Received notification about there being an update for the customgroups app.

@VicDeo @DeepDiver1975

**Comment by DeepDiver1975** [comment]
Assuming this scenario:
- app is not enabled
- updates for the app exist
- admin gets no notifications
- admin enabled app
- worst case scenario: app cannot be enabled or breaks because update is needed to fix
- how does admin know that an update was necessary?

Same workflow with current behavior:
- admin receives notification
- admin at least knows before enabling an out dated app
- breakage risk not that high

Does that make sense?

**Comment by PVince81** [comment]
in that case I'd say there should be a text next to the "enable" button that tells the admin that there is a new version. But then how to do that when enabling on CLI...

You're right... Workaround: uninstall apps that are not used
